
import React from 'react';
import { 
  LayoutDashboard, 
  FileText, 
  Users, 
  Settings, 
  Webhook, 
  BarChart3, 
  LogOut,
  Plus,
  ArrowRight,
  CheckCircle2,
  AlertCircle,
  Copy,
  ExternalLink,
  ChevronRight,
  ChevronLeft,
  Trash2,
  Edit,
  Eye,
  Filter,
  Download,
  ShieldCheck,
  Smartphone,
  MousePointer2,
  Settings2,
  Code,
  Share2,
  Wrench,
  Palette,
  Layers,
  Save,
  UserPlus
} from 'lucide-react';

export const ICONS = {
  Dashboard: <LayoutDashboard size={20} />,
  Forms: <FileText size={20} />,
  Leads: <Users size={20} />,
  Integrations: <Webhook size={20} />,
  Settings: <Settings size={20} />,
  Stats: <BarChart3 size={20} />,
  Logout: <LogOut size={20} />,
  Plus: <Plus size={20} />,
  ArrowRight: <ArrowRight size={20} />,
  Success: <CheckCircle2 size={20} className="text-green-500" />,
  Error: <AlertCircle size={20} className="text-red-500" />,
  Copy: <Copy size={16} />,
  External: <ExternalLink size={16} />,
  ChevronRight: <ChevronRight size={18} />,
  ChevronLeft: <ChevronLeft size={18} />,
  Delete: <Trash2 size={18} />,
  Edit: <Edit size={18} />,
  View: <Eye size={18} />,
  Filter: <Filter size={18} />,
  Download: <Download size={18} />,
  Security: <ShieldCheck size={20} />,
  Mobile: <Smartphone size={20} />,
  Desktop: <MousePointer2 size={20} />,
  Config: <Settings2 size={20} />,
  Code: <Code size={20} />,
  Share: <Share2 size={20} />,
  Tools: <Wrench size={20} />,
  Design: <Palette size={20} />,
  Steps: <Layers size={20} />,
  Save: <Save size={18} />,
  UserPlus: <UserPlus size={18} />
};

export const STANDARD_FIELDS = [
  { label: 'Nome Completo', mappingKey: 'full_name', type: 'text' },
  { label: 'E-mail', mappingKey: 'email', type: 'email' },
  { label: 'Telefone', mappingKey: 'phone', type: 'phone' },
  { label: 'Cidade', mappingKey: 'city', type: 'text' },
  { label: 'Bairro', mappingKey: 'neighborhood', type: 'text' },
  { label: 'Tipo de Imóvel', mappingKey: 'property_type', type: 'select', options: ['Casa', 'Apartamento', 'Terreno', 'Comercial'] },
  { label: 'Objetivo', mappingKey: 'goal', type: 'select', options: ['Comprar', 'Alugar', 'Investir'] },
  { label: 'Orçamento', mappingKey: 'budget', type: 'select', options: ['Até R$ 200k', 'R$ 200k - 500k', 'R$ 500k - 1M', 'Acima de R$ 1M'] }
];
